name: mobile_keyboard_visibility
description: 获取键盘高度
version: 0.0.6
homepage: https://github.com/eyesoffish/mobile_keyboard_visibility

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.mobile_keyboard_visibility
        pluginClass: MobileKeyboardVisibilityPlugin
      ios:
        pluginClass: MobileKeyboardVisibilityPlugin
